// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjfs3kDBlAaKdBhTCAl_fpqbQiO02SS8',
    appId: '1:584283024558:web:db909de98e59dd0715513f',
    messagingSenderId: '584283024558',
    projectId: 'notes-app-df2e4',
    authDomain: 'notes-app-df2e4.firebaseapp.com',
    storageBucket: 'notes-app-df2e4.firebasestorage.app',
    measurementId: 'G-Z0L0Q77C8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXFtwT_vR65iC3njp94bi1ENx5U5cOZQ',
    appId: '1:584283024558:android:9d57e5288f5c09ac15513f',
    messagingSenderId: '584283024558',
    projectId: 'notes-app-df2e4',
    storageBucket: 'notes-app-df2e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB90CSjTRCQ_ixv24bImHP7s4ZO66ljxM',
    appId: '1:584283024558:ios:3fd5bd3ca0ace7b715513f',
    messagingSenderId: '584283024558',
    projectId: 'notes-app-df2e4',
    storageBucket: 'notes-app-df2e4.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB90CSjTRCQ_ixv24bImHP7s4ZO66ljxM',
    appId: '1:584283024558:ios:3fd5bd3ca0ace7b715513f',
    messagingSenderId: '584283024558',
    projectId: 'notes-app-df2e4',
    storageBucket: 'notes-app-df2e4.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHjfs3kDBlAaKdBhTCAl_fpqbQiO02SS8',
    appId: '1:584283024558:web:e0f186d1a5f7073115513f',
    messagingSenderId: '584283024558',
    projectId: 'notes-app-df2e4',
    authDomain: 'notes-app-df2e4.firebaseapp.com',
    storageBucket: 'notes-app-df2e4.firebasestorage.app',
    measurementId: 'G-VVPC8LX18T',
  );
}
